version: '3.2'
services:
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - ./mongo/data:/data/db
        ports:
            - '27017:27017'
    api:
        container_name: api
        restart: unless-stopped
        build: .
        env_file: .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules/
        ports:
            - '8080:8080'
        depends_on:
            - mongo
        links:
            - mongo
